# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f149324ae48c06d256e992432282d28a307e98c5a9085564c02ad216c26fbc0203018aa9f158bd88a6f62f34acdc183469e2f4df21503fe75c9593ff0d5bbf

test:
  secret_key_base: 41c13d744b666d85c3d164535251a9adc707967b0fa1977da017fe6ddeedc178978bcfb010429b062ea6c6016e6296879da53affab193b31c0ec4210562048a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
